#!/usr/bin/env bash

set -euo pipefail

# Determine the full pathname of the directory in which this script lives
function script_dir() {
    (
        local srcpath="${BASH_SOURCE[0]}"
        local scriptdir=
        scriptdir="$(cd -P "$(dirname "${srcpath}")" >/dev/null 2>&1 && pwd || exit)"
        local scriptpath=
        scriptpath="$(realpath "${scriptdir}")"
        echo "${scriptpath}"
    )
}

while read -r testfile; do
    echo "Running test: ${testfile}"
    bash "${testfile}"
done < <(find "$(script_dir)/bin" -mindepth 1 -maxdepth 1 -type f | sort)
