#!/usr/bin/env bash

# Determine the full pathname of the directory in which this script lives
function script-dir() {
    (
        local srcpath="${BASH_SOURCE[0]}"
        local symlinkdir=
        # Resolve symlinks recursively
        while [[ -L "${srcpath}" ]]; do
            # Get symlink directory
            symlinkdir="$(cd -P "$(dirname "${srcpath}")" >/dev/null 2>&1 && pwd || exit)"
            # Resolve symlink target (relative or absolute)
            srcpath="$(readlink "${srcpath}")"
            # Check if candidate path is relative or absolute
            if [[ "${srcpath}" != /* ]]; then
                # Candidate path is relative, resolve to full path
                srcpath="${symlinkdir}/${srcpath}"
            fi
        done
        # Get final script directory path from fully resolved source path
        cd -P "$(dirname "${srcpath}")" >/dev/null 2>&1 || exit
        pwd
    )
}

cd "$(script-dir)" || exit
find . -name '*.test' -prune -print | sort | while read -r test; do
    bash "${test}" || true
done

