#!/usr/bin/env bash
# canonicalize-json: run the full test suite.
#
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
# SPDX-License-Identifier: AGPL-3.0-or-later

set -euo pipefail

whereami=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

bats \
    "${whereami}/01-build.bats" \
    "${whereami}/02-canonicalize.bats" \
    "${whereami}/03-prettify.bats"
