#!/bin/sh

# A containerized JCS (RFC 8785) compliant JSON formatter, utilizing the Python JCS library.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function is_true() {
    echo "${1:?Need argument}" | egrep -iq '^\s*(1|true|t|yes|y)\s*$'
}

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
if is_true "${DEBUG:-false}"; then
    set -o xtrace
    set -o verbose
fi

function prettify() {
    is_true "${PRETTIFY:-${PRETTY_PRINT:-false}}" && (cat /dev/stdin | jq .) || cat /dev/stdin
} 

python /usr/local/bin/canonicalize-json.py | prettify 

