#!/bin/sh
# shellcheck disable=SC3040,SC3041

# A containerized JCS (RFC 8785) compliant JSON formatter, utilizing the Python JCS library.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

is_true() {
    echo "${1:?Need argument}" | grep -Eiq '^\s*(1|on|true|t|yes|y)\s*$'
}

# Set options where supported
(set -E 2>/dev/null) && set -E # -o errtrace
(set -e 2>/dev/null) && set -e # -o errexit
(set -u 2>/dev/null) && set -u # -o nounset
(set -o pipefail 2> /dev/null) && set -o pipefail
if is_true "${DEBUG:-false}"; then
    (set -x 2>/dev/null) && set -x # -o xtrace
    (set -v 2>/dev/null) && set -v # -o verbose
fi

prettify() {
    if is_true "${PRETTIFY:-false}" || is_true "${PRETTY_PRINT:-false}"; then
        cat /dev/stdin | jq .
    else
        cat /dev/stdin
    fi
}

python3 "${__1121CITRUS_APP_DIR}/canonicalize_json.py" | prettify 
